/********************************************************************
* /afs/cern.ch/user/s/soffi/scratch0/CMSSW-8-0-26-p1-CMSPOS2017-MASTER/src/ggAnalysis/ggNtuplizer/macro/Analyzer/AutoDict_vector_vector_float_allocator_float______cxx_ACLiC_dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /afs/cern.ch/user/s/soffi/scratch0/CMSSW-8-0-26-p1-CMSPOS2017-MASTER/src/ggAnalysis/ggNtuplizer/macro/Analyzer/AutoDict_vector_vector_float_allocator_float______cxx_ACLiC_dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableAutoDict_vector_vector_float_allocator_float______cxx_ACLiC_dict();
extern void G__cpp_setup_inheritanceAutoDict_vector_vector_float_allocator_float______cxx_ACLiC_dict();
extern void G__cpp_setup_typetableAutoDict_vector_vector_float_allocator_float______cxx_ACLiC_dict();
extern void G__cpp_setup_memvarAutoDict_vector_vector_float_allocator_float______cxx_ACLiC_dict();
extern void G__cpp_setup_globalAutoDict_vector_vector_float_allocator_float______cxx_ACLiC_dict();
extern void G__cpp_setup_memfuncAutoDict_vector_vector_float_allocator_float______cxx_ACLiC_dict();
extern void G__cpp_setup_funcAutoDict_vector_vector_float_allocator_float______cxx_ACLiC_dict();
extern void G__set_cpp_environmentAutoDict_vector_vector_float_allocator_float______cxx_ACLiC_dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/afs/cern.ch/user/s/soffi/scratch0/CMSSW-8-0-26-p1-CMSPOS2017-MASTER/src/ggAnalysis/ggNtuplizer/macro/Analyzer/AutoDict_vector_vector_float_allocator_float_____.cxx"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__AutoDict_vector_vector_float_allocator_float______cxx_ACLiC_dictLN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__AutoDict_vector_vector_float_allocator_float______cxx_ACLiC_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__AutoDict_vector_vector_float_allocator_float______cxx_ACLiC_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__AutoDict_vector_vector_float_allocator_float______cxx_ACLiC_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__AutoDict_vector_vector_float_allocator_float______cxx_ACLiC_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__AutoDict_vector_vector_float_allocator_float______cxx_ACLiC_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__AutoDict_vector_vector_float_allocator_float______cxx_ACLiC_dictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__AutoDict_vector_vector_float_allocator_float______cxx_ACLiC_dictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__AutoDict_vector_vector_float_allocator_float______cxx_ACLiC_dictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__AutoDict_vector_vector_float_allocator_float______cxx_ACLiC_dictLN_vectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgR;
extern G__linked_taginfo G__AutoDict_vector_vector_float_allocator_float______cxx_ACLiC_dictLN_vectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgRcLcLiterator;
extern G__linked_taginfo G__AutoDict_vector_vector_float_allocator_float______cxx_ACLiC_dictLN_reverse_iteratorlEvectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__AutoDict_vector_vector_float_allocator_float______cxx_ACLiC_dictLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR;
extern G__linked_taginfo G__AutoDict_vector_vector_float_allocator_float______cxx_ACLiC_dictLN_reverse_iteratorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
typedef vector<vector<float,allocator<float> >,allocator<vector<float,allocator<float> > > > G__vectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgR;
typedef vector<vector<float,allocator<float> >,allocator<vector<float,allocator<float> > > >::iterator G__vectorlEvectorlEfloatcOallocatorlEfloatgRsPgRcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRsPgRsPgRcLcLiterator;
