// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in "/afs/cern.ch/user/s/soffi/scratch0/CMSSW-8-0-26-p1-CMSPOS2017-MASTER/src/ggAnalysis/ggNtuplizer/macro/Analyzer/AutoDict_vector_vector_float_allocator_float_____.cxx";

#endif
